"""
app/graph/state.py

Single source of truth for the LangGraph state machine.
Every node reads from and writes to this TypedDict.
"""

from typing import TypedDict, Optional, List, Literal


class Message(TypedDict):
    """A single turn in the conversation history."""
    role: Literal["user", "assistant"]
    content: str


class RetrievedChunk(TypedDict):
    """A document chunk returned from Supabase vector search."""
    chunk_id: str
    content: str
    source: str          # e.g. filename or doc title
    similarity: float    # cosine similarity score


class GraphState(TypedDict):
    """
    Central state passed through every node in the graph.

    Lifecycle:
      Input Node        → sets query, session_id, input_type
      Intent Classifier → sets intent
      Decision Node     → reads intent, routes accordingly
      Retriever Node    → sets retrieved_chunks
      Answer Generator  → sets final_answer
      Clarification     → sets clarification_question, awaiting_clarification
      Memory Update     → appends to chat_history, resets transient fields
    """

    # ── Core input ──────────────────────────────────────────────
    query: str
    """The current user query (text)."""

    session_id: str
    """Unique identifier for the conversation session."""

    input_type: Literal["text", "pdf"]
    """Whether the user sent a plain text query or uploaded a PDF."""

    pdf_path: Optional[str]
    """Local path to the uploaded PDF file (only set when input_type == 'pdf')."""

    # ── Intent classification ────────────────────────────────────
    intent: Optional[Literal["vague", "simple", "complex"]]
    """
    Classified intent of the current query:
      - vague   : ambiguous, needs clarification
      - simple  : can be answered directly without retrieval
      - complex : requires RAG from Supabase
    """

    intent_confidence: Optional[float]
    """Confidence score [0-1] from the intent classifier."""

    # ── Retrieval ────────────────────────────────────────────────
    retrieved_chunks: Optional[List[RetrievedChunk]]
    """Top-k chunks fetched from Supabase pgvector. None if retrieval was skipped."""

    retrieval_filter: Optional[dict]
    """Optional metadata filter passed to Supabase (e.g. {'source': 'report.pdf'})."""

    # ── Generation ───────────────────────────────────────────────
    final_answer: Optional[str]
    """The fully generated assistant response, ready to return to the user."""

    # ── Clarification ────────────────────────────────────────────
    awaiting_clarification: bool
    """True when the graph has asked a follow-up and is waiting for user input."""

    clarification_question: Optional[str]
    """The clarifying question generated by the Clarification Node."""

    # ── Memory / history ─────────────────────────────────────────
    chat_history: List[Message]
    """
    Full ordered conversation history for this session.
    Populated by Memory Update Node after every complete turn.
    Injected back into prompts by Intent Classifier and Answer Generator.
    """

    previous_queries: List[str]
    """Plain list of past user queries — used for deduplication and context."""

    # ── Error handling ───────────────────────────────────────────
    error: Optional[str]
    """Set by any node that encounters a recoverable error. Nodes should check this."""


def initial_state(session_id: str) -> GraphState:
    """
    Returns a clean GraphState for a new session.
    Call this when a session_id is seen for the first time.
    """
    return GraphState(
        query="",
        session_id=session_id,
        input_type="text",
        pdf_path=None,
        intent=None,
        intent_confidence=None,
        retrieved_chunks=None,
        retrieval_filter=None,
        final_answer=None,
        awaiting_clarification=False,
        clarification_question=None,
        chat_history=[],
        previous_queries=[],
        error=None,
    )


def reset_turn(state: GraphState, new_query: str) -> GraphState:
    """
    Resets all transient (per-turn) fields while preserving memory.
    Call this at the start of Input Node for returning users.
    """
    return {
        **state,
        "query": new_query,
        "intent": None,
        "intent_confidence": None,
        "retrieved_chunks": None,
        "retrieval_filter": None,
        "final_answer": None,
        "awaiting_clarification": False,
        "clarification_question": None,
        "error": None,
    }